feat: Adds LE choice when installing debian package.

diff --git a/debian/jitsi-meet-web-config.postinst b/debian/jitsi-meet-web-config.postinst
--- a/debian/jitsi-meet-web-config.postinst
+++ b/debian/jitsi-meet-web-config.postinst
@@ -75,6 +75,7 @@ case "$1" in
         JAAS_INPUT="$RET"
 
         UPLOADED_CERT_CHOICE="I want to use my own certificate"
+        LE_CERT_CHOICE="Let's Encrypt certificates"
         # if first time config ask for certs, or if we are reconfiguring
         if [ -z "$JVB_HOSTNAME_OLD" ] || [ "$RECONFIGURING" = "true" ] ; then
             RET=""
@@ -83,7 +84,7 @@ case "$1" in
             db_get jitsi-meet/cert-choice
             CERT_CHOICE="$RET"
 
-            if [ "$CERT_CHOICE" = "$UPLOADED_CERT_CHOICE" ] ; then
+            if [ "$CERT_CHOICE" = "$UPLOADED_CERT_CHOICE" ]; then
                 RET=""
                 db_get jitsi-meet/cert-path-key
                 if [ -z "$RET" ] ; then
@@ -103,7 +104,7 @@ case "$1" in
                 fi
                 CERT_CRT="$RET"
             else
-                # create self-signed certs
+                # create self-signed certs (we also need them for the case of LE so we can start nginx)
                 CERT_KEY="/etc/jitsi/meet/$JVB_HOSTNAME.key"
                 CERT_CRT="/etc/jitsi/meet/$JVB_HOSTNAME.crt"
                 HOST="$( (hostname -s; echo localhost) | head -n 1)"
@@ -116,6 +117,17 @@ case "$1" in
                     -extensions SAN \
                     -config <(cat /etc/ssl/openssl.cnf \
                         <(printf "[SAN]\nsubjectAltName=DNS:localhost,DNS:$JVB_HOSTNAME"))
+
+                if [ "$CERT_CHOICE" = "$LE_CERT_CHOICE" ]; then
+                    db_subst jitsi-meet/email domain "${JVB_HOSTNAME}"
+                    db_input critical jitsi-meet/email || true
+                    db_go
+                    db_get jitsi-meet/email
+                    EMAIL="$RET"
+                    if [ ! -z "$EMAIL" ] ; then
+                        ISSUE_LE_CERT="true"
+                    fi
+                fi
             fi
         fi
 
@@ -208,12 +220,30 @@ case "$1" in
             invoke-rc.d apache2 reload || true
         fi
 
-        echo "----------------"
-        echo ""
-        echo "You can now switch to a Let’s Encrypt certificate. To do so, execute:"
-        echo "/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh"
-        echo ""
-        echo "----------------"
+        if [ "$ISSUE_LE_CERT" = "true" ] ; then
+            export HOME=/opt/acmesh
+            curl https://get.acme.sh | sh -s email=$EMAIL
+
+            if [ "$FORCE_NGINX" = "true" ]; then
+                RELOAD_CMD="invoke-rc.d nginx force-reload && /usr/share/jitsi-meet/scripts/coturn-le-update.sh ${JVB_HOSTNAME}"
+            elif [ "$FORCE_APACHE" = "true" ]; then
+                RELOAD_CMD="invoke-rc.d apache2 force-reload && /usr/share/jitsi-meet/scripts/coturn-le-update.sh ${JVB_HOSTNAME}"
+            fi
+
+            ISSUE_CERT_CMD="/opt/acmesh/.acme.sh/acme.sh --issue -d $JVB_HOSTNAME -w /usr/share/jitsi-meet --server letsencrypt"
+            eval $ISSUE_CERT_CMD || ISSUE_FAILED="true"
+
+            INSTALL_CERT_CMD="/opt/acmesh/.acme.sh/acme.sh --install-cert -d $JVB_HOSTNAME --key-file /etc/jitsi/meet/$JVB_HOSTNAME.key --fullchain-file /etc/jitsi/meet/$JVB_HOSTNAME.crt --reloadcmd \"$RELOAD_CMD\""
+            if [ "$ISSUE_FAILED" = "true" ] ; then
+                echo "Issuing the certificate from Let's Encrypt failed, continuing ..."
+                echo "You can retry later by executing:"
+                echo "$ISSUE_CERT_CMD"
+                echo "$INSTALL_CERT_CMD"
+                echo ""
+            else
+                eval $INSTALL_CERT_CMD
+            fi
+        fi
 
         if [ "${JAAS_INPUT}" != "true" ]; then
             echo ""
