fix(debian) make sure we install the latest version of luajwtjitsi
Also on update, since we might start depending on a more recent version.

diff --git a/debian/jitsi-meet-tokens.postinst b/debian/jitsi-meet-tokens.postinst
--- a/debian/jitsi-meet-tokens.postinst
+++ b/debian/jitsi-meet-tokens.postinst
@@ -48,6 +48,11 @@ case "$1" in
         db_stop
 
         if [ -f "$PROSODY_HOST_CONFIG" ] ; then
+            # Install luajwt (also on update, to make sure we get the latest version).
+            if ! luarocks install luajwtjitsi 3.0-0; then
+               echo "Failed to install luajwtjitsi - try installing it manually"
+            fi
+
             # search for the token auth, if this is not enabled this is the
             # first time we install tokens package and needs a config change
             if ! egrep -q '^\s*authentication\s*=\s*"token"' "$PROSODY_HOST_CONFIG"; then
@@ -59,16 +64,6 @@ case "$1" in
                 sed -i "s/ --app_secret=\"example_app_secret\"/ app_secret=\"$APP_SECRET\"/g" $PROSODY_HOST_CONFIG
                 sed -i 's/ --modules_enabled = { "token_verification" }/ modules_enabled = { "token_verification" }/g' $PROSODY_HOST_CONFIG
                 sed -i '/^\s*--\s*"token_verification"/ s/--\s*//' $PROSODY_HOST_CONFIG
-
-                # Install luajwt
-                if ! luarocks install luajwtjitsi 3.0-0; then
-                   echo "Failed to install luajwtjitsi - try installing it manually"
-                fi
-
-                # Install basexx
-                if ! luarocks install basexx; then
-                   echo "Failed to install basexx - try installing it manually"
-                fi
 
                 PR10_INSTALL_CHECK="$(dpkg-query -f '${Status}' -W 'prosody-0.10' 2>/dev/null | awk '{print $3}' || true)"
                 PRTRUNK_INSTALL_CHECK="$(dpkg-query -f '${Status}' -W 'prosody-trunk' 2>/dev/null | awk '{print $3}' || true)"
